### PR TITLE
Balance Model DIP

### PR DESCRIPTION
**Pull request by redpartyhat**

### CODE REVIEW

**Comment by AeonSw4n** [comment]
Looking good! A much needed change.

**Comment by tijno** [comment]
First off good to see a DIP being raised for this. I was concerned by the complete lack of engagement with DIPs - so I am hopeful that this change will help revert that trend.

For example - #113 raised questions about move to balance model and never got any response from any of the core team ... until now. 

Some of these seemed to be covered in this DIP but not all.

> * will UTXOs be removed completely?

Reading the DIP UTXO - am I correct in my understanding that UTXO will continue to exist for transactions prior to `BalanceModelBlockHeight` ?

> * pros & cons

This DIP talks mainly about negative sides of UTXO, but does not cover the positives. As Bitcoin has been designed from the start with UTXO and to my knowledge this has never changed - what are the beneficial aspects of UTXO that will be lost by a move to Balance model?

I would like to see some more info in this DIP about the pros and cons of UTXO vs Balance model. At the moment it seems to largely cover pros and cons of the required changes , rather then the actual core of this DIP which is the move from UTXO to Balance.

> * impact on scalability

I think this will helps scalability as transaction size will decrease - but would be good to see this articulated. Recent issues with trying to transfer collected node fees is an example I guess of the downside of UTXO on scalability.

> * risks for community developed tools

I hope that community engagement with this DIP will help to bring out these risks and minimise downtime.

In addition to the above:

1. Balance verification before and after change

We need to make sure that sum of balances of unspent transactions / locked deso is consistent with A) total supply, and B) the post change balance model. I think it would be beneficial if the backend api had a way of verifying this too at any time. See also [Total Supply Calc](https://github.com/deso-protocol/docs/issues/14). The total supply calc before change is complicated because of [this outstanding issue as well](https://github.com/deso-protocol/core/issues/46).

2. How to ensure transition/fork without trouble

Almost every single major change that was rolled out on DESO caused downtime on tools, nodes and exchanges for no doubt a variety of different reasons.

Ones the DIP is approved, what are the anticipated timescales for the change to allow adequate testing ?

**Review by maebeam — APPROVED** [review]

**Comment by maebeam** [comment]
My only question is what exactly happens at the block height? Are UTXO transactions still accepted after the block height? Does there need to be a second block height disabling UTXO transactions?

**Comment by arhebbar** [comment]
> First off good to see a DIP being raised for this. I was concerned by the complete lack of engagement with DIPs - so I am hopeful that this change will help revert that trend.

Echo this completely. It is great to see this and I hope it is used by the core team as a way to show the community devs that they are part of the team and also hopefully will encourage more community devs to start contributing back to core. 

> > * risks for community developed tools
...
> 2. How to ensure transition/fork without trouble
> 
> Almost every single major change that was rolled out on DESO caused downtime on tools, nodes and exchanges for a variety of different reasons.

This one is huge. I really hope there's a plan in place and all the major tools and dApps that get impacted is brought onto the discussion so that this doesn't create a PR disaster with people losing money, confusion around it, needing to revert the changes, etc.  In that regard, it would be good to put a broad timeline of when this change is expected so that the community can plan accordingly. For example, hold off on working on some changes until this is live, etc. This comment is both for this change and for all work that the team is doing.  But, more so for this DIP.

**Comment by tijno** [comment]
🤬 whats the point even trying & sharing views?

clearly decision was made way before this DIP was posted and clearly the only ones that have to follow your process are outsiders.

3 weeks ago work on this started - https://github.com/deso-protocol/core/commits/rph/balance-model

**Review by diamondhands0 — APPROVED** [review]
Looks like an excellent proposal.

**Comment by tijno** [comment]
@diamondhands0 You didn't see my replies? Or did you just decide to ignore and throw community engagement in the bin?

**Comment by diamondhands0** [comment]
Hey @tijno, sorry I missed your comments! I'm sure @redpartyhat will address them prior to merging this DIP. Generally, it's the responsibility of the DIP proposer to address all comments before they merge it, so I can assure you they won't be ignored.

**Comment by redpartyhat** [comment]
@tijno Thank you so much for all the feedback and many apologies for the slow response! We are hard at work on a number of initiatives to support the DeSo community, not least of which is aggressively hiring an A+ team to better support processes like this one. Building an ecosystem that developers and apps thrive in is our #1 priority for 2022 and I hope that we do you proud.

Now, it is no secret that I have been working on this balance model change in a branch when I have spare time. This has been incredibly helpful for me in understanding how difficult this change would be to implement and what exactly needs to happen. Sometimes I find that it's easier to understand a change by just jumping into the code and getting started. For example, I would never have realized that TransactionBundle serialization would break without running the tests since Block serialization is unaffected. We had no intent to merge this branch without a thorough discussion (hence the DIP) and a significant amount of warning. And in our defense, I think there is something to be said for moving fast and breaking things in order to iterate more quickly while the chain is in its infancy. Every feature that we add now is going to make DeSo that much more unbeatable in the future.  The time we have now, before more marquee exchange listings enforce additional process on hard forks, is invaluable.

Here are the answers to your more technical questions:

> Will UTXOs be removed completely?

I address this in the backwards compatibility section of the DIP: "This change will create a hard fork as it will no longer support transactions that have UTXO inputs." In other words, yes, UTXOs will be removed completely. We will leave the existing UTXOs in the database for now but they will no longer be added or deleted.  We will rely on the balance model index instead.

> Reading the DIP - am I correct in my understanding that UTXO will continue to exist for transactions prior to BalanceModelBlockHeight?

Correct, all historical transactions would continue to operate in the same way. 

> This DIP talks mainly about negative sides of UTXO, but does not cover the positives. As Bitcoin has been designed from the start with UTXO and to my knowledge this has never changed - what are the beneficial aspects of UTXO that will be lost by a move to Balance model?

This is a great point. The main benefit of the UTXO model is that it provides extremely reliable financial tracking. It is hard for the code to accidentally print money when every nano being spent must specify exactly where it came from. However, we feel that thorough testing and sanity checks for core code changes will provide sufficient security. Ethereum and Solana are great examples of this, both have operated very effectively on the balance model. Not to mention, there are many key players (e.g. exchanges) in the DeSo community that are constantly monitoring the DESO in circulation to ensure that the code is operating as expected.

> I think this will helps scalability as transaction size will decrease - but would be good to see this articulated in some more detail.

Impact on transaction size will vary depending on the number of UTXOs attached to the transaction. However, looking at a simple basic transfer with only one UTXO is fairly informative. In this scenario, the serialized transaction would include bytes for: the input, the output, and the signature. The input would be 34 bytes (1 byte to specify the number of inputs, 32 bytes for the txn hash, and 1 byte for the txn index), the output would be 35 bytes (1 byte to specify the number of outputs, 33 bytes for the public key, 1 byte for the amount), and the signature would be ~71 bytes long. In this simple scenario, the single UTXO takes up about 25% of the transaction size. As more UTXOs are added, they can quickly dominate the size of the transaction. This transaction bloat has serious implications with regard to sync times, transaction costs, and database storage requirements.

> Balance verification before and after change.

It turns out that we already have a powerful tool for balance verification thanks to Coinbase.  We implemented their rosetta API early on in the development of the chain (see the "rosetta-deso" repo) and the rosetta-cli comes with balance reconciliation tools. If balances change unexpectedly from one block to the next the rosetta reconciliation check will hold us accountable.

> How to ensure transition/fork without trouble

Since this fork is a particularly serious infrastructure change, we will be setting the BalanceModelBlockHeight to something that provides ample time for everyone to upgrade. We will also be manually notifying developers of well-known apps (such as tijn.club!) to ensure that they are able to seemlessly transition to the new transaction type.  In addition, we plan to use test net in order to test this hard fork before it enters the wild, which we have not had the ability to do in the past. We also hope that more devs will examine the DIP and associated code change and flag any concerns. The more eyes, the better.

> Once the DIP is approved, what are the anticipated timescales for the change to allow adequate testing?

This is an open question for debate. There is no rush to roll this change out. However, a longer timeline will inevitable delay other infrastructure changes such as Proof of Stake, Warp Sync, Coin Split, etc.  

> Accounts cant have negative balances? Currently postgres sync on current blockchain still has negative balances in the pg_balances table.

I am not up to speed with the work being done on postgres but negative balances are absolutely not allowed.

> Impact on other planned changes? Most notably: A) coin split, B) move to proof of stage, C) DRC-20, and D) SQL.

I do not expect this to have any implications with regard to other planned changes. If anything, it will make implementation easier as dealing with UTXOs adds significant complexity.  For example, staking a portion of one's balance is significantly easier than staking a list of specific UTXOs.

I will add the relevant portions of my responses above to the draft DIP. Thanks again!

**Comment by HPaulson** [comment]
@redpartyhat Thanks a ton for this information -- we do truly appreciate it. My only thing:
> We had no intent to merge this branch without a thorough discussion (hence the DIP) and a significant amount of warning. 

While I understand that right now it's vital to iterate and move quickly while requirements are low, and your intentions may have been to still wait until discussion here to merge, it's still important to have community members in the loop *during* development, not just when we're ready to merge. Of course, your team had discussions internally about this change ages ago, weighing pros and cons, measuring the plan, etc. While it's fine for this to occur within the team, it's important to include the community too. Rather than creating a DIP after development, create it when these internal talks are occurring instead, giving community members a way to provide insight maybe the team didn't even think of. Then of course during development, you will learn new things about what the change affects, at which point you can update the DIP and ensure we have an understanding of how development is progressing. Not to mention other benefits: Spotting mistakes in code is much easier when looking at small commits through time, rather than one massive PR. 

I'm sure I speak for all of us when I say this would be a much more effective manner to update the chain. I've had plenty of conversations with engineers in the space, especially over this week, and quite a few of us were worrying that we'd end up in a place like we were in at the beginning of summer. There's no need for that. Ya'll have been killing it in the past few months, let's keep the ball rolling. Just don't leave us in the dark until last minute (Especially when it's a fork!!)

**Comment by tijno** [comment]
thx @redpartyhat for the detailed reply - sorry been really busy so have not had a time until today to review.

I appreciate the improvements your looking to make to the process. Definately needed and I hope the team is successful in hiring the A+ developers/team to support this.

All that said

How do we avoid valid questions raised by me and others - well before this DIP was raised - dont get missed by the team?

#113 I tagged you and @diamondhands0 in that and got no engagement. What can I do next time to get an issue on your radar?

> We had no intent to merge this branch without a thorough discussion (hence the DIP) and a significant amount of warning

Ok - maybe next time flag that up in the DIP? I do get it and it makes a lot of sense. 

Sudden merges are just a sensitive point ever since the midnight soft fork right at the start!

> UTXOs will be removed completely

Ok.

> It is hard for the code to accidentally print money when every nano being spent must specify exactly where it came from. 

Ok. With the recent double spend vulnerability I guess stuff like that exists either way - whether its balance or utxo. I hope the A+ team being hired includes some deep blockchain security/vulnerability expertise.

> the rosetta-cli comes with balance reconciliation tools. If balances change unexpectedly from one block to the next the rosetta reconciliation check will hold us accountable.

Great news!  Also @lazynina addition of total circulation & top 1000 balances is very useful for this.

> We also hope that more devs will examine the DIP and associated code change 

Me too! How can we get this more exposure? Most devs are kinda ignoring DIPs now due to lack of core team engagement and feedback on their DIPs in the past.

> I will add the relevant portions of my responses above to the draft DIP. 

I dont think this has been done yet?

> Missing Block 0 on chain

I suggest this issue with current chain / explorer is resolved prior to a move ahead with this DIP.

See here https://github.com/deso-protocol/core/issues/21 and https://github.com/deso-protocol/core/issues/46 and https://tijn.club/posts/e994aa7ea0f5d7dd7f0b643dfeb0a606a8eefa01061dc66773ed1b4f9bd9e24a

**Pull request merged**
