### PR TITLE
This proposal introduces a new paradigm called DAO Coins to the DeSo ecosystem

### PR DESCRIPTION
**Pull request by diamondhands0**
I'm especially interested in feedback around:
* What, if any, limitations the current proposal would place on app developers. What would you want to build that you can't build with this current proposal?
* The way we propose to allow for optional restrictions on transfers
* If there are any fundraising models that would *not* be feasible with this approach
* The interplay between DAO Coins and Creator Coins
* Our thinking around secondary liquidity for DAO coins

### CODE REVIEW

**Comment by brootle** [comment]
I have no idea what is DAO, and I am now even more confused about DAO coins, if somebody makes 2 min video on this subject, please, tag me! Thanks! 🙏

**Comment by diamondhands0** [comment]
@brootle mainstream version comes out next week :)

**Comment by summraznboi** [comment]
> Require approval on transfers to new members.
Does this mean to any user that has ever owned a DAO coin, or just currently? The quote above implied former, the description in the announcement implies latter (unrestricted among existing holders).

**Comment by Bobnificent** [comment]
Currently holding the DAO coin

**Comment by alanzucker** [comment]
I am very excited to see this proposal.  And I understand and concur with the timeframe for implementation.  I am hoping, for clarity, that you could help someone who has... (looks up self on ProsperClout) ... 175 days experience with blockchain based apps.  What DAO data will be on-chain, and what data will not?  Is there a schema that will be applied to provide some structure to the data and pointers to where it may be stored?

I hope I am not being a pest with these questions.  I am on the learning curve and putting in the effort to progress rapidly so that I can be a contributor to this awesome endeavor.

**Comment by AdonousTech** [comment]
First, this sounds awesome. 

_What, if any, limitations the current proposal would place on app developers. What would you want to build that you can't build with this current proposal?_

This seems to be exactly what I need for my project (@VOSO). However, I do have concerns with the identity of the coin. So, can we have a $VOSO creator coin and a $VOSO DAO coin, or will that be a conflict?

The way we propose to allow for optional restrictions on transfers

I like the new capabilities for DAO coins that extend beyond creator coins. So, if we restrict further minting on the DAO coin, is that action reversible?

_The interplay between DAO Coins and Creator Coins_

See my first question.

Our thinking around secondary liquidity for DAO coins

Without concrete examples of the Smart Services integration, its hard to imagine how implementing a secondary market for the DAO coin transactions would work. However, I particularly like the idea of the DAO coins being initially non-transferrable as the main purpose is for raising capital.

**Comment by PineappleClout** [comment]
Excited to build on this. Have been waiting, was going to fork the chain myself 🤣

@DAObase is a decentralized web3 app built on the $DeSo protocol backend that is used to exchange $DeSo DAO coins. DAObase facilitates automated transactions between DAO coins on the DeSo blockchain through the use of social contracts.

More info coming soon 🔜

🍍👐

**Comment by Lux1n** [comment]
I’m overall very excited for this proposal and what it will unlock as far as on-chain organization and fundraising.

One concern I have about the function that turns off transferability of coins is that someone could airdrop a coin to DAO members, rename the coin to something malicious, and then lock the transfer and/or sell function.

**Comment by deso2021** [comment]
really excited for it ! and I have some question:

> Disable minting of DAO coins: 

this function is permanent and irreversible?

> delegated via derived keys 

what is derived keys ? and how it work in technically

**Comment by summraznboi** [comment]
> what is derived keys ? and how it work in technically

See https://docs.deso.org/identity/mobile-integration

**Comment by arhebbar** [comment]
> Once a profile is created, the following very simple on-chain functions become available on the profile:
> - Minting and Burning Coins
> - Burn DAO coins: This function can be executed by anyone to take coins they own out of circulation.
> - Disable minting of DAO coins: ...
> - Require approval on all transfers*. ...
> - Require approval on transfers to new members. 
> - Turn off all transfer restrictions. ...
> - Permanently disable all transfer restrictions. ...


Should these functions only be accessible on the original creation of the DAO? Or at least before the first investment comes into the DAO. I personally wouldn't want to invest in any DAO where the Owner can make these decisions without the consensus of the DAO. Not sure how it is setup in other DAO tools, but worth looking into I believe.

Maybe a compromise could be that it can be done the first time by the Owner with some fields that are changeable. And those that are changed later on are changed with the consensus of the DAO.

**Comment by Lux1n** [comment]
Will DAO coins cost DeSo in fees to issue? One example laid out in this initial doc proposed 100 mill coins being minted, why would that cost?

**Comment by Lux1n** [comment]
> Will DAO coins cost DeSo in fees to issue? One example laid out in this initial doc proposed 100 mill coins being minted, why would that cost?

What would that cost*

**Comment by Netikitt** [comment]
My concerns are related to my adoption of DeSo and attempts at creating a project from use cases to wireframes then development. 

My account is Netikitt, and I set up NetikittDAO using NFT's for the first round, the hierarchy based on the initial price for the C level. 

The intent was twofold; build an Organization for consensus and fundraise. 

So I'll ask my questions regarding these two fundamentals; 

**Consensus:** My thought is you would have the ability to tier the DAO coin based on initial needs. 

**Example:** building the highest structure, a final vote and decision making. For instance, that DAOc coin may be set at a $10,000 initial offering. (DAOb, DAOa, DAOf)

**Fundraising:** My thought is a DAOf coin separates the needs between consensus and fundraising. 

And allowing the project to collect the funds without being seen as a rug puller. 

So funds can be distributed to the project's needs, in my case, development. 

And for others, it may be a dividend payout?

**Comment by bloated-devish** [comment]
Question regarding account offering both DAO and creator coin. Can a good use case be provided where its impossible to confuse between the 2 coins for the users? 

Given the security implications, most people are likely to keep these 2 accounts separate even though derived keys gives some amount of safety net.

I really wonder in terms of product simplicity - could we create a separate profile type called DAO and offer these - so people never have the product problem of confusing DAO coin and creator coin. It coudl be possible to provide link to the creator coin account in the DAO account. Internally, in the chain the treatment can be vastly different, but for users, its super clear - they are either buying coin of a project / company or they are buying coin of a user.

**Comment by kuririn1** [comment]
I think that simple on-chain order book implementation should be included from the get-go. It will allow creating dexes and will be much more secure. In other cases cex or smart service will need to hold the assets and it will be responsible for the funds. It will be a huge security burden. The centralized exchange could hold a significant amount of coins at any given time in their wallets that could be hacked. It will also facilitate more transactions, because people will trust it more than sending their coins to the centralized exchange (service).

For me, benefits (security) are much greater than the bloat of the chain (and a little bit longer wait time).

Possible implementation:
* buy and sell orders - the amount of coins, the price and type of transaction (sell, buy) - transaction type order, orders could be canceled
* if matched they fill automatically with partial filling too, for example: "buy 10 XYZ coins for 4.5" will match "sell 20 XYZ coins for 4.2" (limit order) - transaction type trade
* API endpoints to list orders on particular pairs (order book) etc. (I could plan this if there is a need)

The community will do the rest - I'm happy to create an interface for such a dex, maybe even in form of a DAO.

Other order types could be added in the future.

**Comment by alanzucker** [comment]
Here is a project/app that this proposal precludes.  
DeSo Film Sprints
A club where amateur and professional filmmakers work on each other's short films for free.  In each sprint, film scripts are pitched, produced, edited, screened, and voted on.  Winning films get budget for the next sprint.   Films made within the sprints are owned entirely by the filmmakers, not the DAO.

How DAO Coins precludes this project:
The project needs DAO governance and DeSo social features.  The project explicitly CAN NOT have the promise of ROI for members of the DAO.   The Film Sprint DAO, in and of itself, can not be investment vehicle.  The term "DAO Coins" carries with it a strong implication that an ROI is a potentiality.  

Clearly the inspiration for DAO Coins is financial.  The DIP uses language like "founder" "startup" and "raising money."  My feedback is that there is much greater potential benefit for the DeSo Protocol if this new product were called something more neutral... like "DAO Tokens" or "DAO Membership."  Additionally terminology such as "invest" and "reward" in documents surrounding this project could be made more neutral.

There are myriad types of potential non-ROI apps that could utilize DAO governance to bring mass-activity onto the DeSo protocol... changing the world for the better.

**Comment by deso2021** [comment]
> 

dex idea is amazing, It is a key function to improve liquidity. Expect us to have it.

**Comment by darian-parrish** [comment]
1. What would you want to build that you can't build with this current proposal?

A branched governance model where different types of DAO tokens enable different branches or groups within the DAO to have different permissions. Under this proposal would  be handled in the app layer but could only easily do hierarchical structures with magnitude of holdings defining roles(without maintaining off chain roles) or implement a more complicated sub-DAO structure.

2. Thoughts on optional restrictions on transfers:

Great and needed. There will be some accidental uses of the permanent functions but that is the most critical one.

3. Any fundraising models not feasible with this approach:

No. Because it is pretty open-ended since this doesn't define governance. Could accept any asset in exchange for DAO tokens - just not built in(to be handled p2p on trust or a smart service). Would be nice to have at least a single way to purchase DAO tokens directly. For example set a price and have an automated treasury exchange.

4. Thoughts on interplay between DAO Coins and Creator Coins:

Two potential issues - first is what others have mentioned as the confusion bit which could probably be solved with good UI/UX.  The second is that CC sand DAO coins have no automated bridge/ relationship. Everything happens manually based on trust.

The only reasons it makes sense to have both simultaneously: a) to bootstrap fundraising and b) to allow automated funding via CCs since no automated treasury is planned for the DAO coins. It seems like this might be a shortcut that causes more pain in the long run - maybe more discussion needed.

5. Thinking around secondary liquidity for DAO coins:
 
Tough one… secondary liquidity so important

Focus says right to leave this up to the builders to handle via smart services... but having an on-chain order-book exchange for DAO coins would be such a unique competitive advantage…

**Comment by Netikitt** [comment]
> A branched governance model where different types of DAO tokens enable different branches or groups within the DAO to have different permissions. Under this proposal would be handled in the app layer but could only easily do hierarchical structures with magnitude of holdings defining roles(without maintaining off chain roles) or implement a more complicated sub-DAO structure.

**Love this!** ❤

**Comment by hisabness** [comment]
How will alternative layer 1 funds be integrated and managed as a part of a treasury? Say a supporter wants to contribute sol USDC and/or the DAO has some need for USDC to pay for resources, pay bills, etc. Will Deso allow for that?

**Comment by hisabness** [comment]
Alternatively, will deso have a stable coin of some sort that can be used in a treasury for DAOs?

**Comment by hisabness** [comment]
Multisig x of n, seems like another potential issue. Very few DAOs are run by one individual.

**Comment by diamondhands0** [comment]
Thank you to everyone who provided feedback! I just went through every comment above. With everything that's been proposed and discussed, I think we're ready to move forward with the implementation.

Below are some topics that were brought up, and my thoughts:

- How would one reward dividends to DAO-holders?
  * One would write a script or use a smart service to distribute DESO or some other coin to all of the holders of the DAO. One could also distribute Bitcoin, ETH or some other currency via this method. They are not limited to just DeSo assets.
- What DAO data will be on-chain?
  * The DAO cap table (who owns what coins, and how many) as well as the standard DeSo social information like the profile of the DAO and the holders, as well as any posts from the DAO, etc...
- Can you have a creator coin and a DAO coin?
  * Yes you can
- After you disable minting, is further minting disabled forever?
  * Yes it is. This is the point. You want a way to be able to guarantee your holders that you aren't going to inflate the supply at some point in the future.
- What if I accidentally disable minting or mess something up?
  * It's very onerous, but you would have to create a new profile for your DAO, airdrop the new coins to everyone, and get them to accept the new profile as the "true" DAO. You basically have to "hard fork" your DAO.
- Can we have the DAO vote on things like enabling transfer restrictions?
  * All examples of DAOs we've seen are controlled on-chain by a multisig rather than having on-chain votes actually change parameters on-chain. However, in addition to this, DAOs we've seen execute off-chain votes via tools like Snapshot in order to get consensus around decisions. So the short answer is: On-chain the DAO will be controlled by a multisig, but off-chain votes can be used to decide on DAO parameters. This is state of the art.
- Will DAO coins cost DESO in fees to be minted?
 * Virtually zero fees just like everything else on DeSo :)
- Lots of comments about having a tiered structure for governance.
  * We think you can achieve this either with multiple DAO coins via multiple profiles OR by issuing NFTs under the DAO that control things. For example, if you wanted a "senate" and a "house of representatives", you could achieve this with 100 "Senate NFTs" and 435 "House of Representative NFTs." You could then conduct votes of the holders of these NFTs.
- Will people confuse Creator Coins and DAO Coins?
  * We think the UX will solve for this. As long as UI's like Diamond have a clear distinction there shouldn't be any confusion. They serve very different use-cases. Creator Coins are for people, DAO coins are for organizaitons.
- You guys love the on-chain order book :)
  * I wouldn't say it's out of the question that we'd implement the basics for an order book on-chain. After some discussion, it would only take a few days, and the smart service would still be useful for matching orders in a trustless fashion. However, we can add this later at any time.
- How will alternative layer 1 funds be integrated and managed as a part of a treasury?
  * All examples we've seen, including ConstitutionDAO, manage their treasury with a multisig. We will have the same.

**Comment by HPaulson** [comment]
@diamondhands0 Per this PR & the associated release schedule, I'd like to know if there are plans to assign a human-readable name to the fork. As we've seen with other protocols, assigning a human-readable name to forks (Example: London Hard Fork) provides benefits for reporting, developer conversations, and makes a solid reference tag within commit history. Has the team assigned a name, and if so, what is it? If not -- can you potentially think about that, and start using it in reference to the fork?

- HP

**Pull request merged**
